language: python
cache: pip
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
before_install:
  - wget https://github.com/antirez/redis/archive/5.0-rc5.tar.gz && tar -xvzf 5.0-rc5.tar.gz && cd redis-5.0-rc5 && make && src/redis-server --daemonize yes && cd ..
  - redis-cli info
env:
  - TEST_HIREDIS=0
  - TEST_HIREDIS=1
install:
  - pip install -e .
  - "if [[ $TEST_PEP8 == '1' ]]; then pip install pycodestyle; fi"
  - "if [[ $TEST_HIREDIS == '1' ]]; then pip install hiredis; fi"
script: "if [[ $TEST_PEP8 == '1' ]]; then pycodestyle --repeat --show-source --exclude=.venv,.tox,dist,docs,build,*.egg .; else python setup.py test; fi"
matrix:
  include:
    - python: "2.7"
      env: TEST_PEP8=1
    - python: "3.6"
      env: TEST_PEP8=1
